import { Award, LockKeyhole, Sparkles } from "lucide-react";
import GameLayout from "@/components/GameLayout";
import { achievements } from "@/lib/game-data";
import { useGame } from "@/contexts/GameContext";

export default function Achievements() {
  const { player } = useGame();
  return <GameLayout title="Achievement vault" eyebrow="PROGRESSION // BADGES"><div className="container py-7 sm:py-9"><section className="rounded-3xl border border-violet-300/18 bg-gradient-to-br from-violet-400/[.12] via-[#0d1422] to-cyan-300/[.06] p-6 sm:p-8"><p className="font-mono text-[10px] tracking-[.2em] text-violet-200">ACHIEVEMENT VAULT</p><div className="mt-4 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><h2 className="font-display text-3xl font-bold tracking-[-.04em] text-white">Collect proof of <span className="text-violet-300">progress.</span></h2><p className="mt-3 max-w-xl text-sm leading-6 text-slate-400">Every badge marks a specific action you took in the simulation—not just a score.</p></div><div className="rounded-2xl border border-white/[.1] bg-black/15 p-4 text-center"><p className="font-mono text-2xl font-semibold text-cyan-200">{player.achievements.length}<span className="text-slate-600">/9</span></p><p className="mt-1 font-mono text-[9px] tracking-[.12em] text-slate-500">BADGES UNLOCKED</p></div></div></section>
      <section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{achievements.map((achievement) => { const unlocked = player.achievements.includes(achievement.id); return <article key={achievement.id} className={`relative overflow-hidden rounded-2xl border p-5 ${unlocked ? "border-cyan-300/25 bg-gradient-to-br from-cyan-300/[.1] to-violet-400/[.07]" : "border-white/[.08] bg-white/[.025]"}`}><div className="flex items-start justify-between"><span className={`grid h-11 w-11 place-items-center rounded-xl text-lg ${unlocked ? "bg-cyan-300/15 text-cyan-100 shadow-[0_0_28px_rgba(34,211,238,.12)]" : "bg-white/[.05] text-slate-600"}`}>{unlocked ? achievement.icon : <LockKeyhole className="h-4 w-4" />}</span>{unlocked && <Sparkles className="h-4 w-4 text-violet-200" />}</div><h3 className={`mt-7 text-sm font-bold ${unlocked ? "text-white" : "text-slate-400"}`}>{achievement.title}</h3><p className="mt-2 min-h-12 text-xs leading-5 text-slate-500">{achievement.description}</p><div className="mt-4 border-t border-white/[.07] pt-3 font-mono text-[9px] tracking-[.09em] text-slate-500">{unlocked ? "UNLOCKED" : `REQUIRES: ${achievement.requirement.toUpperCase()}`}</div></article> })}</section>
      <section className="mt-7 rounded-2xl border border-white/[.08] bg-[#0d1422]/75 p-5"><div className="flex items-start gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-amber-300/10 text-amber-200"><Award className="h-4 w-4" /></span><div><p className="text-sm font-semibold text-white">Badge signals are local in this prototype</p><p className="mt-1 text-sm leading-6 text-slate-400">The application is already structured to attach these achievements to university accounts when the society enables sign-in and persistence.</p></div></div></section>
    </div></GameLayout>;
}
