import { FormEvent, useState } from "react";
import { BarChart3, Check, Plus, Power, ShieldAlert, Users } from "lucide-react";
import GameLayout from "@/components/GameLayout";
import EventClaimsPanel from "@/components/EventClaimsPanel";
import { missions } from "@/lib/game-data";

type Draft = { title: string; category: string; xp: string };

export default function Admin() {
  const [active, setActive] = useState<Record<string, boolean>>(() => Object.fromEntries(missions.map((mission) => [mission.id, true])));
  const [draft, setDraft] = useState<Draft>({ title: "", category: "Password Security", xp: "100" });
  const [created, setCreated] = useState<Draft[]>([]);
  const submit = (event: FormEvent) => {
    event.preventDefault();
    if (!draft.title.trim()) return;
    setCreated((current) => [...current, draft]);
    setDraft({ title: "", category: "Password Security", xp: "100" });
  };
  const total = missions.length + created.length;

  return <GameLayout title="Society console" eyebrow="ADMIN PROTOTYPE // COMMITTEE ONLY"><div className="container py-7 sm:py-9">
    <section className="rounded-3xl border border-rose-300/18 bg-gradient-to-br from-rose-400/[.09] via-[#0d1422] to-violet-400/[.08] p-6 sm:p-8"><div className="flex items-start gap-4"><span className="grid h-11 w-11 place-items-center rounded-xl border border-rose-300/20 bg-rose-300/[.08] text-rose-200"><ShieldAlert className="h-5 w-5" /></span><div><p className="font-mono text-[10px] tracking-[.2em] text-rose-200">SOCIETY COMMITTEE CONSOLE</p><h2 className="mt-2 font-display text-2xl font-bold text-white">Manage the learning environment.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Manage mission state, create local drafts and, for administrator accounts, review consented ISACA invitation claims. Competition results are validated server-side.</p></div></div></section>
    <section className="mt-7 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border border-white/[.08] bg-[#0d1422]/75 p-5"><BarChart3 className="h-5 w-5 text-cyan-300" /><p className="mt-7 font-mono text-2xl text-white">72%</p><p className="mt-1 font-mono text-[9px] tracking-[.13em] text-slate-500">AVG. MISSION COMPLETION</p></div><div className="rounded-2xl border border-white/[.08] bg-[#0d1422]/75 p-5"><Users className="h-5 w-5 text-violet-300" /><p className="mt-7 font-mono text-2xl text-white">127</p><p className="mt-1 font-mono text-[9px] tracking-[.13em] text-slate-500">DEMO ACTIVE AGENTS</p></div><div className="rounded-2xl border border-white/[.08] bg-[#0d1422]/75 p-5"><Check className="h-5 w-5 text-emerald-300" /><p className="mt-7 font-mono text-2xl text-white">{total}</p><p className="mt-1 font-mono text-[9px] tracking-[.13em] text-slate-500">MISSION RECORDS</p></div></section>
    <section className="mt-7 grid gap-7 xl:grid-cols-[1.1fr_.9fr]"><div className="rounded-2xl border border-white/[.08] bg-[#0d1422]/75 p-5"><div className="flex items-center justify-between"><div><p className="font-mono text-[10px] tracking-[.16em] text-cyan-300">MISSION DIRECTORY</p><h3 className="mt-1 font-semibold text-white">Activate or pause simulations</h3></div><span className="font-mono text-[10px] text-slate-500">LOCAL STATE</span></div><div className="mt-5 space-y-2">{missions.map((mission) => <div key={mission.id} className="flex items-center justify-between gap-3 rounded-xl border border-white/[.06] bg-white/[.025] p-3"><div><p className="text-sm font-medium text-white">{mission.title}</p><p className="mt-1 font-mono text-[9px] text-slate-500">{mission.category.toUpperCase()} · {mission.xp} XP</p></div><button onClick={() => setActive((current) => ({ ...current, [mission.id]: !current[mission.id] }))} className={`inline-flex items-center gap-1.5 rounded-lg px-2.5 py-2 font-mono text-[9px] transition ${active[mission.id] ? "bg-emerald-300/[.09] text-emerald-300" : "bg-rose-300/[.08] text-rose-200"}`}><Power className="h-3.5 w-3.5" /> {active[mission.id] ? "ACTIVE" : "PAUSED"}</button></div>)}{created.map((mission, index) => <div key={`${mission.title}-${index}`} className="flex items-center justify-between rounded-xl border border-cyan-300/16 bg-cyan-300/[.05] p-3"><div><p className="text-sm font-medium text-cyan-100">{mission.title}</p><p className="mt-1 font-mono text-[9px] text-slate-500">{mission.category.toUpperCase()} · {mission.xp} XP</p></div><span className="font-mono text-[9px] text-cyan-300">DRAFT</span></div>)}</div></div>
      <form onSubmit={submit} className="rounded-2xl border border-white/[.08] bg-[#0d1422]/75 p-5"><div className="flex items-center gap-2"><Plus className="h-4 w-4 text-violet-300" /><div><p className="font-mono text-[10px] tracking-[.16em] text-violet-300">MISSION BUILDER</p><h3 className="mt-1 font-semibold text-white">Create a local draft</h3></div></div><label className="mt-5 block"><span className="font-mono text-[9px] tracking-[.12em] text-slate-500">MISSION TITLE</span><input value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} required placeholder="e.g. Decode the beacon" className="mt-2 h-10 w-full rounded-lg border border-white/[.1] bg-[#070b14] px-3 text-sm text-white outline-none transition placeholder:text-slate-600 focus:border-cyan-300/60" /></label><label className="mt-4 block"><span className="font-mono text-[9px] tracking-[.12em] text-slate-500">CATEGORY</span><select value={draft.category} onChange={(event) => setDraft({ ...draft, category: event.target.value })} className="mt-2 h-10 w-full rounded-lg border border-white/[.1] bg-[#070b14] px-3 text-sm text-slate-200 outline-none focus:border-cyan-300/60"><option>Password Security</option><option>Social Engineering</option><option>Incident Investigation</option><option>Web Security</option><option>Multiple Skills</option><option>GRC &amp; Assurance</option></select></label><label className="mt-4 block"><span className="font-mono text-[9px] tracking-[.12em] text-slate-500">XP REWARD</span><input value={draft.xp} onChange={(event) => setDraft({ ...draft, xp: event.target.value })} inputMode="numeric" className="mt-2 h-10 w-full rounded-lg border border-white/[.1] bg-[#070b14] px-3 text-sm text-white outline-none focus:border-cyan-300/60" /></label><button type="submit" className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-violet-300 px-4 py-3 text-xs font-bold text-[#130b22] transition hover:bg-violet-200"><Plus className="h-4 w-4" /> ADD LOCAL DRAFT</button><p className="mt-3 text-center font-mono text-[9px] text-slate-600">PERSISTENCE CAN BE ENABLED WITH THE INCLUDED DATABASE TABLES.</p></form></section>
    <EventClaimsPanel />
  </div></GameLayout>;
}
