import { ArrowRight, CheckCircle2, Crosshair, Fingerprint, ShieldCheck, Sparkles, TerminalSquare } from "lucide-react";
import { Link } from "wouter";
import GameLayout from "@/components/GameLayout";

const steps = [
  { number: "01", icon: Fingerprint, title: "Read the situation", text: "Start with a fictional incident, suspicious message, terminal session, browser console, or simulated network capture. The context is part of the puzzle." },
  { number: "02", icon: TerminalSquare, title: "Investigate the clues", text: "Use the local tools provided by the mission: inspect evidence, enter safe terminal commands, replay a request, analyse headers, or correlate a timeline." },
  { number: "03", icon: Crosshair, title: "Make the decision", text: "Submit a finding, classify a message, capture a flag, harden a browser boundary, or choose the proportionate defensive action." },
  { number: "04", icon: ShieldCheck, title: "Unpack the why", text: "After completion, the debrief explains the security concept, how an attacker might abuse it, and the controls defenders use to reduce the risk." },
];

const rules = [
  "Every environment is fictional and sandboxed. No real systems, accounts, networks, or websites are contacted.",
  "The terminal and browser tools accept only predefined local simulation commands; they are not operating-system or network shells.",
  "Progress and achievements are stored locally in your browser for this static GitHub Pages version.",
  "Hints are optional on introductory missions. Advanced missions are designed for independent investigation with no hints.",
];

export default function HowItWorks() {
  return <GameLayout title="How it works" eyebrow="FIELD GUIDE // START HERE" actions={<span className="rounded-full border border-cyan-300/20 bg-cyan-300/[.07] px-3 py-1.5 font-mono text-[10px] text-cyan-200">SAFE SIMULATION</span>}><div className="container py-8 sm:py-12">
    <section className="relative overflow-hidden rounded-3xl border border-cyan-300/18 bg-gradient-to-br from-cyan-300/[.1] via-[#0d1422] to-violet-400/[.1] p-6 sm:p-10"><div className="absolute -right-16 -top-16 h-56 w-56 rounded-full bg-cyan-300/[.08] blur-3xl" /><div className="relative max-w-3xl"><p className="font-mono text-[10px] tracking-[.2em] text-cyan-300">THE FIELD GUIDE</p><h2 className="mt-3 font-display text-4xl font-black tracking-[-.05em] text-white sm:text-5xl">No lectures. Just <span className="text-violet-300">curiosity.</span></h2><p className="mt-5 max-w-2xl text-base leading-7 text-slate-300">Cyber Security Society turns core security ideas into investigations. Follow the signals, test your thinking, and learn the defensive reasoning behind every answer.</p></div></section>
    <section className="mt-8 grid gap-4 md:grid-cols-2">{steps.map(({ number, icon: Icon, title, text }) => <article key={number} className="rounded-2xl border border-white/[.08] bg-white/[.025] p-6 transition hover:border-cyan-300/25 hover:bg-white/[.045]"><div className="flex items-start justify-between"><span className="font-mono text-sm text-cyan-300">{number}</span><Icon className="h-5 w-5 text-violet-300" /></div><h3 className="mt-8 text-xl font-bold text-white">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-400">{text}</p></article>)}</section>
    <section className="mt-8 grid gap-6 xl:grid-cols-[1fr_.85fr]"><div className="rounded-2xl border border-white/[.08] bg-[#0d1422]/75 p-6"><div className="flex items-center gap-3"><Sparkles className="h-5 w-5 text-amber-300" /><div><p className="font-mono text-[10px] tracking-[.16em] text-amber-200">MISSION PATH</p><h3 className="mt-1 text-lg font-bold text-white">Choose your difficulty</h3></div></div><div className="mt-6 space-y-4"><div><p className="text-sm font-semibold text-cyan-100">Starter missions</p><p className="mt-1 text-sm leading-6 text-slate-400">Passwords, phishing, incident timelines, and a fictional web lab introduce the foundations.</p></div><div><p className="text-sm font-semibold text-violet-100">Advanced missions</p><p className="mt-1 text-sm leading-6 text-slate-400">Terminal forensics, browser security, API authorization, and packet correlation require multi-step reasoning.</p></div><div><p className="text-sm font-semibold text-emerald-100">Debrief and progress</p><p className="mt-1 text-sm leading-6 text-slate-400">Complete missions to earn XP, unlock achievements, and build a local agent profile.</p></div></div></div><div className="rounded-2xl border border-emerald-300/16 bg-emerald-300/[.045] p-6"><CheckCircle2 className="h-5 w-5 text-emerald-300" /><p className="mt-5 font-mono text-[10px] tracking-[.16em] text-emerald-200">SAFETY FIRST</p><h3 className="mt-2 text-lg font-bold text-white">Learn safely, think deeply.</h3><ul className="mt-5 space-y-3 text-sm leading-6 text-slate-400">{rules.map((rule) => <li key={rule} className="flex gap-2"><span className="text-emerald-300">›</span><span>{rule}</span></li>)}</ul></div></section>
    <div className="mt-8 flex flex-wrap gap-3"><Link href="/missions" className="rounded-xl bg-cyan-300 px-5 py-3 text-xs font-bold text-[#06111d] transition hover:bg-cyan-200">EXPLORE MISSIONS <ArrowRight className="ml-1 inline h-4 w-4" /></Link><Link href="/" className="rounded-xl border border-white/[.12] bg-white/[.04] px-5 py-3 text-xs font-semibold text-white transition hover:bg-white/[.08]">BACK TO HOME</Link></div>
  </div></GameLayout>;
}
