import { useState } from "react";
import { Crown, Medal, TrendingUp } from "lucide-react";
import GameLayout from "@/components/GameLayout";
import { leaderboard } from "@/lib/game-data";
import { useGame } from "@/contexts/GameContext";

export default function Leaderboard() {
  const [period, setPeriod] = useState("This Week");
  const { player, level } = useGame();
  const playerRow = ["—", "Cyber Recruit", `${level}`, player.xp.toLocaleString(), player.completed.length.toString(), player.achievements.length.toString()];
  return <GameLayout title="Cyber leaderboard" eyebrow="COMMUNITY // PRACTICE RANKINGS"><div className="container py-7 sm:py-9"><section className="overflow-hidden rounded-3xl border border-amber-300/15 bg-gradient-to-br from-amber-300/[.07] via-[#0d1422] to-violet-400/[.08] p-6 sm:p-8"><div className="flex flex-col justify-between gap-7 md:flex-row md:items-end"><div><p className="font-mono text-[10px] tracking-[.2em] text-amber-200">CYBER LEADERBOARD</p><h2 className="mt-3 font-display text-3xl font-bold tracking-[-.04em] text-white">Practice. Learn. <span className="text-amber-200">Climb.</span></h2><p className="mt-3 max-w-xl text-sm leading-6 text-slate-400">Demo agents make the SOC feel alive. Your position updates locally as you complete missions.</p></div><div className="flex rounded-xl border border-white/[.1] bg-black/15 p-1">{["This Week", "This Month", "All Time"].map((item) => <button key={item} onClick={() => setPeriod(item)} className={`rounded-lg px-3 py-2 text-xs transition ${period === item ? "bg-white/[.1] text-white" : "text-slate-500 hover:text-slate-300"}`}>{item}</button>)}</div></div></section>
      <section className="mt-7 grid gap-4 md:grid-cols-3">{leaderboard.slice(0, 3).map((entry, index) => <div key={entry[1]} className={`rounded-2xl border p-5 ${index === 0 ? "border-amber-300/25 bg-amber-300/[.06]" : "border-white/[.08] bg-white/[.025]"}`}><div className="flex items-center justify-between"><span className="font-mono text-xs text-slate-500">RANK {entry[0]}</span>{index === 0 ? <Crown className="h-5 w-5 text-amber-200" /> : <Medal className="h-5 w-5 text-slate-400" />}</div><p className="mt-8 font-display text-xl font-bold text-white">{entry[1]}</p><p className="mt-1 font-mono text-[10px] text-cyan-300">LEVEL {entry[2]} · {entry[3]} XP</p></div>)}</section>
      <section className="mt-5 overflow-hidden rounded-2xl border border-white/[.08] bg-[#0d1422]/75"><div className="grid grid-cols-[.4fr_1.6fr_.7fr_.9fr_.8fr_.7fr] gap-2 border-b border-white/[.07] px-4 py-3 font-mono text-[9px] tracking-[.12em] text-slate-500 sm:px-6"><span>RANK</span><span>PLAYER</span><span>LEVEL</span><span>XP</span><span>MISSIONS</span><span>BADGES</span></div>{leaderboard.map((entry) => <div key={entry[1]} className="grid grid-cols-[.4fr_1.6fr_.7fr_.9fr_.8fr_.7fr] gap-2 border-b border-white/[.055] px-4 py-4 text-xs transition hover:bg-white/[.035] sm:px-6"><span className="font-mono text-slate-500">{entry[0]}</span><span className="font-semibold text-white">{entry[1]}</span><span className="font-mono text-slate-400">{entry[2]}</span><span className="font-mono text-violet-200">{entry[3]}</span><span className="font-mono text-slate-400">{entry[4]}</span><span className="font-mono text-slate-400">{entry[5]}</span></div>)}<div className="grid grid-cols-[.4fr_1.6fr_.7fr_.9fr_.8fr_.7fr] gap-2 border-t border-cyan-300/20 bg-cyan-300/[.06] px-4 py-4 text-xs sm:px-6"><span className="font-mono text-cyan-300">{playerRow[0]}</span><span className="font-semibold text-cyan-100">{playerRow[1]}</span><span className="font-mono text-cyan-100">{playerRow[2]}</span><span className="font-mono text-violet-200">{playerRow[3]}</span><span className="font-mono text-cyan-100">{playerRow[4]}</span><span className="font-mono text-cyan-100">{playerRow[5]}</span></div></section><p className="mt-4 flex items-center gap-2 font-mono text-[10px] text-slate-500"><TrendingUp className="h-3.5 w-3.5 text-emerald-300" /> Demo standings — persistence-ready layout for future society accounts.</p></div></GameLayout>;
}
