import { useMemo, useState } from "react";
import { Link } from "wouter";
import { Filter, LockKeyhole, Search, Sparkles } from "lucide-react";
import GameLayout from "@/components/GameLayout";
import MissionCard from "@/components/MissionCard";
import { missions } from "@/lib/game-data";
import { useGame } from "@/contexts/GameContext";

export default function Missions() {
  const { player } = useGame();
  const [filter, setFilter] = useState("All missions");
  const [query, setQuery] = useState("");
  const categories = ["All missions", "Beginner", "Investigation", "Web Security", "Social Engineering"];
  const shown = useMemo(() => missions.filter((mission) => (filter === "All missions" || mission.difficulty.includes(filter.toUpperCase()) || mission.category.includes(filter)) && `${mission.title} ${mission.category} ${mission.description}`.toLowerCase().includes(query.toLowerCase())), [filter, query]);
  const escapeUnlocked = player.completed.length >= 3;
  return <GameLayout title="Mission control" eyebrow="OPS // SELECT A SIMULATION"><div className="container py-7 sm:py-9"><section className="relative overflow-hidden rounded-3xl border border-white/[.09] bg-gradient-to-br from-[#101b2d] via-[#0d1423] to-violet-500/[.12] p-6 sm:p-8"><div className="absolute -right-16 -top-20 h-64 w-64 rounded-full bg-violet-400/[.13] blur-3xl" /><div className="relative"><p className="font-mono text-[10px] tracking-[.2em] text-cyan-300">MISSION CONTROL</p><h2 className="mt-3 font-display text-3xl font-bold tracking-[-.04em] text-white sm:text-4xl">Choose your next <span className="text-violet-300">challenge.</span></h2><p className="mt-3 max-w-xl text-sm leading-6 text-slate-400">Every environment is fictional, local and deliberately designed to teach a defensive security idea through discovery.</p><div className="mt-7 flex flex-wrap items-center gap-3"><div className="rounded-xl border border-white/[.1] bg-[#060a12]/50 px-3 py-2 font-mono text-[10px] text-slate-300"><Sparkles className="mr-1.5 inline h-3.5 w-3.5 text-violet-300" /> {player.completed.length}/6 MISSIONS CLEARED</div><div className="rounded-xl border border-white/[.1] bg-[#060a12]/50 px-3 py-2 font-mono text-[10px] text-slate-300"><LockKeyhole className="mr-1.5 inline h-3.5 w-3.5 text-cyan-300" /> {escapeUnlocked ? "ESCAPE ROOM UNLOCKED" : "CLEAR 3 MISSIONS FOR ESCAPE ROOM"}</div></div></div></section>
      <div className="mt-7 flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-wrap gap-2" role="tablist" aria-label="Mission filters">{categories.map((category) => <button key={category} onClick={() => setFilter(category)} className={`rounded-full px-3.5 py-2 text-xs font-semibold transition ${filter === category ? "bg-cyan-300 text-[#06111d]" : "border border-white/[.09] bg-white/[.035] text-slate-400 hover:border-white/[.18] hover:text-white"}`}>{category}</button>)}</div><label className="flex w-full items-center gap-2 rounded-xl border border-white/[.09] bg-white/[.025] px-3 lg:w-60"><Search className="h-4 w-4 text-slate-500" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search missions" className="h-10 min-w-0 flex-1 bg-transparent text-xs text-white outline-none placeholder:text-slate-600" /></label></div>
      <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{shown.map((mission) => <MissionCard key={mission.id} mission={{ ...mission, status: mission.id === "escape-room" && escapeUnlocked ? "available" : mission.status }} completed={player.completed.includes(mission.id)} featured={mission.id === "guess-my-password"} />)}</div>
      {shown.length === 0 && <div className="mt-6 rounded-2xl border border-dashed border-white/[.12] p-10 text-center"><Filter className="mx-auto h-6 w-6 text-slate-600" /><p className="mt-3 text-sm text-slate-400">No mission signals match that filter.</p><button onClick={() => { setFilter("All missions"); setQuery(""); }} className="mt-3 text-xs font-semibold text-cyan-300">Clear filters</button></div>}
      <section className="mt-8 grid gap-4 lg:grid-cols-[.9fr_1.1fr]"><div className="rounded-2xl border border-cyan-300/15 bg-cyan-300/[.05] p-5"><p className="font-mono text-[10px] tracking-[.17em] text-cyan-300">FIRST-TIME RECRUIT?</p><h3 className="mt-3 text-lg font-bold text-white">You don’t need to know how to hack.</h3><p className="mt-2 text-sm leading-6 text-slate-400">You only need curiosity. Mission 01 is designed so you can score your first win in a few minutes.</p><Link href="/missions/guess-my-password" className="mt-4 inline-block text-xs font-bold text-cyan-200 hover:text-cyan-100">Launch Mission 01 →</Link></div><div className="rounded-2xl border border-white/[.08] bg-white/[.025] p-5"><p className="font-mono text-[10px] tracking-[.17em] text-slate-500">SAFETY BOUNDARY</p><p className="mt-3 text-sm leading-6 text-slate-300">This is an educational simulation. It never scans real websites, receives real credentials, or runs arbitrary commands. Every target, login, email and log shown here is fictional.</p></div></section>
    </div></GameLayout>;
}
