import { Activity, BadgeCheck, BookOpenCheck, RotateCcw, Shield, Target } from "lucide-react";
import GameLayout from "@/components/GameLayout";
import { skillCards } from "@/lib/game-data";
import { useGame } from "@/contexts/GameContext";

export default function Profile() {
  const { player, level, levelTitle, resetDemo } = useGame();
  const progress = (player.xp % 500) / 5;
  return <GameLayout title="Agent profile" eyebrow="IDENTITY // CYBER RECRUIT"><div className="container py-7 sm:py-9"><section className="relative overflow-hidden rounded-3xl border border-cyan-300/18 bg-gradient-to-br from-[#102038] via-[#0d1422] to-cyan-300/[.08] p-6 sm:p-8"><div className="absolute -right-12 -top-12 h-48 w-48 rounded-full border border-cyan-300/10" /><div className="relative flex flex-col justify-between gap-6 md:flex-row md:items-end"><div className="flex items-center gap-5"><span className="grid h-20 w-20 place-items-center rounded-2xl border border-cyan-300/25 bg-cyan-300/[.1] font-display text-2xl font-bold text-cyan-100 shadow-[0_0_40px_rgba(34,211,238,.12)]">CR</span><div><p className="font-mono text-[10px] tracking-[.18em] text-cyan-300">AGENT ID: SOC-0001</p><h2 className="mt-2 font-display text-3xl font-bold tracking-[-.04em] text-white">Cyber Recruit</h2><p className="mt-1 text-sm text-slate-400">Level {level} · {levelTitle}</p></div></div><div className="grid grid-cols-3 divide-x divide-white/[.08] rounded-xl border border-white/[.09] bg-black/15 p-3 text-center"><div className="px-4"><p className="font-mono text-lg text-white">{player.xp.toLocaleString()}</p><p className="font-mono text-[8px] tracking-[.12em] text-slate-500">XP</p></div><div className="px-4"><p className="font-mono text-lg text-white">{player.completed.length}/5</p><p className="font-mono text-[8px] tracking-[.12em] text-slate-500">MISSIONS</p></div><div className="px-4"><p className="font-mono text-lg text-white">{player.achievements.length}/8</p><p className="font-mono text-[8px] tracking-[.12em] text-slate-500">BADGES</p></div></div></div></section>
      <section className="mt-7 grid gap-7 xl:grid-cols-[.9fr_1.1fr]"><div className="rounded-2xl border border-white/[.08] bg-[#0d1422]/75 p-5"><div className="flex items-center gap-2"><Target className="h-4 w-4 text-cyan-300" /><h3 className="font-semibold text-white">XP progression</h3></div><p className="mt-6 font-display text-4xl font-bold text-white">{player.xp.toLocaleString()} <span className="text-lg font-medium text-slate-500">XP</span></p><div className="mt-5 flex justify-between font-mono text-[10px] text-slate-500"><span>LEVEL {level}</span><span>{player.xp % 500} / 500 XP TO LEVEL {level + 1}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/[.07]"><div className="h-full rounded-full bg-gradient-to-r from-cyan-300 to-violet-400" style={{ width: `${progress}%` }} /></div><p className="mt-5 text-sm leading-6 text-slate-400">Clear missions with fewer hints to maximise the XP you earn from future challenges.</p></div><div className="rounded-2xl border border-white/[.08] bg-[#0d1422]/75 p-5"><div className="flex items-center gap-2"><Shield className="h-4 w-4 text-violet-300" /><h3 className="font-semibold text-white">Skill development</h3></div><div className="mt-4 grid gap-x-8 sm:grid-cols-2">{skillCards.map((skill) => <div key={skill.name} className="border-b border-white/[.06] py-3"><div className="flex justify-between text-xs"><span className="text-slate-300">{skill.name}</span><span className="font-mono text-cyan-200">LEVEL {skill.level}</span></div><div className="mt-2 flex gap-1">{Array.from({ length: 5 }).map((_, index) => <span key={index} className={`h-1.5 flex-1 rounded-full ${index < skill.level ? "bg-cyan-300" : "bg-white/[.08]"}`} />)}</div></div>)}</div></div></section>
      <section className="mt-7 grid gap-7 xl:grid-cols-2"><div><div className="mb-4 flex items-center gap-2"><Activity className="h-4 w-4 text-emerald-300" /><h3 className="font-semibold text-white">Recent activity</h3></div><div className="rounded-2xl border border-white/[.08] bg-[#0d1422]/75 p-2">{player.recentActivity.map((activity, index) => <div key={`${activity}-${index}`} className="flex gap-3 rounded-xl p-4"><span className="mt-1.5 h-2 w-2 rounded-full bg-cyan-300" /><div><p className="text-sm text-slate-200">{activity}</p><p className="mt-1 font-mono text-[9px] text-slate-500">LOCAL DEMO PROGRESS</p></div></div>)}</div></div><div><div className="mb-4 flex items-center gap-2"><BookOpenCheck className="h-4 w-4 text-amber-200" /><h3 className="font-semibold text-white">Prototype controls</h3></div><div className="rounded-2xl border border-white/[.08] bg-[#0d1422]/75 p-5"><p className="text-sm font-semibold text-white">Testing a mission flow?</p><p className="mt-2 text-sm leading-6 text-slate-400">Reset only this browser's demo XP, badge and mission state. This does not affect other students or any future production data.</p><button onClick={resetDemo} className="mt-5 inline-flex items-center gap-2 rounded-xl border border-rose-300/25 bg-rose-300/[.06] px-3.5 py-2.5 text-xs font-semibold text-rose-200 transition hover:bg-rose-300/[.12]"><RotateCcw className="h-4 w-4" /> Reset demo progress</button></div></div></section>
    </div></GameLayout>;
}
